src/Entity/Sponsor.php
<?php

namespace App\Entity;

use App\Repository\SponsorRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=SponsorRepository::class)
 */
class Sponsor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *  @Assert\Length(
     *      min = 3,
     *      max = 10,
     *      minMessage = "Entrez plus que 3 lettres",
     *      maxMessage = "Entrez moins de 10 lettres"
     * )
     * @Assert\NotBlank(message="Le champ nom est obligatoire * ")
     * @ORM\Column(type="string", length=255)
     */
    private $nom_sponsor;

    /**
     *  @Assert\Length(
     *      min = 3,
     *      max = 10,
     *      minMessage = "Entrez plus que 3 lettres",
     *      maxMessage = "Entrez moins de 10 lettres"
     * )
     * @Assert\NotBlank(message="Le champ prenom est obligatoire * ")
     * @ORM\Column(type="string", length=255)
     */
    private $prenom_sponsor;

    /**
     *  @Assert\Length(
     *      min = 8,
     *      max = 8,
     *      minMessage = "Entrez 8 chiffres",
     *      maxMessage = "Entrez 8 chiffres"
     * )
     * @Assert\NotBlank(message="Le champ num est obligatoire * ")
     * @ORM\Column(type="integer")
     */
    private $num_sponsor;

    /**
     * @Assert\NotBlank(message="Le champ type est obligatoire * ")
     * @ORM\Column(type="string", length=255)
     */
    private $type_sponsor;

    /**
     * @ORM\Column(type="integer")
     */
    private $event_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSponsor(): ?string
    {
        return $this->nom_sponsor;
    }

    public function setNomSponsor(string $nom_sponsor): self
    {
        $this->nom_sponsor = $nom_sponsor;

        return $this;
    }

    public function getPrenomSponsor(): ?string
    {
        return $this->prenom_sponsor;
    }

    public function setPrenomSponsor(string $prenom_sponsor): self
    {
        $this->prenom_sponsor = $prenom_sponsor;

        return $this;
    }

    public function getNumSponsor(): ?int
    {
        return $this->num_sponsor;
    }

    public function setNumSponsor(int $num_sponsor): self
    {
        $this->num_sponsor = $num_sponsor;

        return $this;
    }

    public function getTypeSponsor(): ?string
    {
        return $this->type_sponsor;
    }

    public function setTypeSponsor(string $type_sponsor): self
    {
        $this->type_sponsor = $type_sponsor;

        return $this;
    }

    public function getEventId(): ?int
    {
        return $this->event_id;
    }

    public function setEventId(int $event_id): self
    {
        $this->event_id = $event_id;

        return $this;
    }
}

src/Form/SponsorType.php
<?php

namespace App\Form;

use App\Entity\Sponsor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class SponsorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_sponsor')
            ->add('prenom_sponsor')
            ->add('num_sponsor')
            ->add('type_sponsor', ChoiceType::class, [
                'choices'  => [
                    'matériel' => "matériel",
                    'immatériel' => "immatériel",

                ],
            ])
            ->add('event_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sponsor::class,
        ]);
    }
}

src/Controller/SponsorController.php
<?php

namespace App\Controller;

use App\Entity\Sponsor;
use App\Form\SponsorType;
use App\Repository\SponsorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use MercurySeries\FlashyBundle\FlashyNotifier;

/**
 * @Route("/sponsor")
 */
class SponsorController extends AbstractController
{
    /**
     * @Route("/", name="app_sponsor_index", methods={"GET"})
     */
    public function index(SponsorRepository $sponsorRepository): Response
    {
        return $this->render('sponsor/index.html.twig', [
            'sponsors' => $sponsorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_sponsor_new", methods={"GET", "POST"})
     */
    public function new(Request $request, SponsorRepository $sponsorRepository): Response
    {
        $sponsor = new Sponsor();
        $form = $this->createForm(SponsorType::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sponsorRepository->add($sponsor);
            $this->addFlash('info', 'Ajout avec succés !');
            return $this->redirectToRoute('app_sponsor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('sponsor/new.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_sponsor_show", methods={"GET"})
     */
    public function show(Sponsor $sponsor): Response
    {
        return $this->render('sponsor/show.html.twig', [
            'sponsor' => $sponsor,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_sponsor_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Sponsor $sponsor, SponsorRepository $sponsorRepository): Response
    {
        $form = $this->createForm(SponsorType::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sponsorRepository->add($sponsor);
            $this->addFlash('info', 'Modification avec succés !');
            return $this->redirectToRoute('app_sponsor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('sponsor/edit.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_sponsor_delete", methods={"POST"})
     */
    public function delete(Request $request, Sponsor $sponsor, SponsorRepository $sponsorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sponsor->getId(), $request->request->get('_token'))) {
            $sponsorRepository->remove($sponsor);
            $this->addFlash('info', 'supression avec succés !');
        }

        return $this->redirectToRoute('app_sponsor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/sponsor/_delete_form.html.twig
<form method="post" action="{{ path('app_sponsor_delete', {'id': sponsor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sponsor.id) }}">
    <button class="btn btn-fill-out btn-block">Delete</button>
</form>

templates/sponsor/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
    {{ form_widget(form) }}

<div class="container d-flex flex-column align-items-center">
    <button class="btn btn-fill-out btn-block">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/sponsor/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Sponsor{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Edit Sponsor</h1>

    {{ include('sponsor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_sponsor_index') }}" class="btn btn-fill-out btn-block">back to list</a>

    {{ include('sponsor/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/sponsor/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Sponsor{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Sponsor</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_sponsor</th>
                <th>Prenom_sponsor</th>
                <th>Num_sponsor</th>
                <th>Type_sponsor</th>
                <th>Event_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sponsor in sponsors %}
            <tr>
                <td>{{ sponsor.id }}</td>
                <td>{{ sponsor.nomSponsor }}</td>
                <td>{{ sponsor.prenomSponsor }}</td>
                <td>{{ sponsor.numSponsor }}</td>
                <td>{{ sponsor.typeSponsor }}</td>
                <td>{{ sponsor.eventId }}</td>
                <td>
                    <a href="{{ path('app_sponsor_show', {'id': sponsor.id}) }}" class="btn btn-fill-out btn-block">show</a>
                    <a href="{{ path('app_sponsor_edit', {'id': sponsor.id}) }}" class="btn btn-fill-out btn-block">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_sponsor_new') }}" class="btn btn-fill-out btn-block">Create new</a>
</div>
{% endblock %}

templates/sponsor/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Sponsor{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Create new Sponsor</h1>

    {{ include('sponsor/_form.html.twig') }}

    <a href="{{ path('app_sponsor_index') }}" class="btn btn-fill-out btn-block">back to list</a>
</div>
{% endblock %}

templates/sponsor/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Sponsor{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Sponsor</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sponsor.id }}</td>
            </tr>
            <tr>
                <th>Nom_sponsor</th>
                <td>{{ sponsor.nomSponsor }}</td>
            </tr>
            <tr>
                <th>Prenom_sponsor</th>
                <td>{{ sponsor.prenomSponsor }}</td>
            </tr>
            <tr>
                <th>Num_sponsor</th>
                <td>{{ sponsor.numSponsor }}</td>
            </tr>
            <tr>
                <th>Type_sponsor</th>
                <td>{{ sponsor.typeSponsor }}</td>
            </tr>
            <tr>
                <th>Event_id</th>
                <td>{{ sponsor.eventId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_sponsor_index') }}" class="btn btn-fill-out btn-block">back to list</a>

    <a href="{{ path('app_sponsor_edit', {'id': sponsor.id}) }}" class="btn btn-fill-out btn-block">edit</a>

    {{ include('sponsor/_delete_form.html.twig') }}
</div>
{% endblock %}