src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *  @Assert\Length(
     *      min = 3,
     *      max = 10,
     *      minMessage = "Entrez plus que 3 lettres",
     *      maxMessage = "Entrez moins de 10 lettres"
     * )
     * @Assert\NotBlank(message="Le champ nom est obligatoire * ")
     * @ORM\Column(type="string", length=255)
     */
    private $nom_event;

    /**
     * @ORM\Column(type="string", length=255)

     */
    private $image;
    /**
     * @Assert\PositiveOrZero
     * @Assert\NotBlank(message="Le champ nombre de participants est obligatoire * ")
     * @ORM\Column(type="integer")
     */
    private $nbr_participant;

    /**


     * @ORM\Column(name="date_debut", type="date")



     */
    private $date_debut;

    /**

     * @ORM\Column(name="date_fin", type="date")



     */
    private $date_fin;

    /**
     *  @Assert\Length(
     *      min = 3,
     *      max = 100,
     *      minMessage = "Entrez plus que 3 lettres",
     *      maxMessage = "Entrez moins de 10 lettres"
     * )
     * @Assert\NotBlank(message="Le champ emplacement est obligatoire * ")
     * @ORM\Column(type="string", length=255)
     */
    private $emplacement;

    /**
     *  @Assert\Length(
     *      min = 10,
     *      max = 50,
     *      minMessage = "Entrez plus que 10 lettres",
     *      maxMessage = "Entrez moins de 50 lettres"
     * )
     * @Assert\NotBlank(message="Le champ description est obligatoire * ")
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     *  @Assert\Length(
     *      min = 3,
     *      max = 15,
     *      minMessage = "Entrez plus que 3 lettres",
     *      maxMessage = "Entrez moins de 10 lettres"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $theme;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEvent(): ?string
    {
        return $this->nom_event;
    }

    public function setNomEvent(string $nom_event): self
    {
        $this->nom_event = $nom_event;

        return $this;
    }

    public function getNbrParticipant(): ?int
    {
        return $this->nbr_participant;
    }

    public function setNbrParticipant(int $nbr_participant): self
    {
        $this->nbr_participant = $nbr_participant;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getEmplacement(): ?string
    {
        return $this->emplacement;
    }

    public function setEmplacement(string $emplacement): self
    {
        $this->emplacement = $emplacement;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }
    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_event')
            ->add('nbr_participant')
            ->add('date_debut')
            ->add('date_fin')
            ->add('emplacement')
            ->add('description')

            ->add('theme', ChoiceType::class, [
                'choices'  => [
                    'Gastronomie' => "Gastronomie",
                    'Cinéma' => "Cinéma",
                    'Industriel' => "Industriel",
                ],
            ])
            ->add('image', FileType::class, ['label' =>'image '])
        ;
    }



    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\RequestStack;
use Dompdf\Dompdf;
use Knp\Component\Pager\PaginatorInterface;
use Dompdf\Options;


/**
 * @Route("/evenement")
 */
class EvenementController extends AbstractController
{
    
    /**
     * @Route("/", name="app_evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $pagination = $paginator->paginate( $evenementRepository->findAll(), $request->query->getInt('page',1), 4);
        return $this->render('evenement/index.html.twig', [
            'evenements' => $pagination,
        ]);
    }
    /**
     * @Route("/listp/{id}", name="listp")
     */
    public function listp(Evenement $evenement)
    {$pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);


        $Evenement = $this->getDoctrine()->getRepository(Evenement::class)->findAll();


        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('evenement/listp.html.twig', ["evenement" => $Evenement]);

        // Load HTML to Dompdf

        $dompdf->loadHtml($html);


        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);

    }


    /**
     * @Route("/new", name="app_evenement_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EvenementRepository $evenementRepository): Response
    {

        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $evenement->getImage();
            $fileName = md5(uniqid()).'.'.$file->guessExtension();
            $this->addFlash('info', 'Ajout avec succés !');
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $entityManager = $this->getDoctrine()->getManager();
            $evenement->setImage($fileName);
            $entityManager->persist($evenement);
            $entityManager->flush();
            $evenementRepository->add($evenement);
            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }
    /**
     * @Route("/new", name="app_event_ticket", methods={"GET", "POST"})
     */
    public function ticket(Request $request, EvenementRepository $evenementRepository): Response
    {

        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $evenement->getImage();
            $fileName = md5(uniqid()).'.'.$file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $entityManager = $this->getDoctrine()->getManager();
            $evenement->setImage($fileName);
            $entityManager->persist($evenement);
            $entityManager->flush();
            $evenementRepository->add($evenement);
            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}/edit", name="app_evenement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Evenement $evenement, EvenementRepository $evenementRepository): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $evenementRepository->add($evenement);

            $this->addFlash('info', 'modification avec succés !');
            return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_evenement_delete", methods={"POST"})
     */
    public function delete(Request $request, Evenement $evenement, EvenementRepository $evenementRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $evenementRepository->remove($evenement);
            $this->addFlash('info', 'supression avec succés !');
            

        }


        return $this->redirectToRoute('app_evenement_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route ("/" , name="app_event_show_front" , methods={"GET"})
     */
    public function affi(){
        $list=$this->getDoctrine()->getRepository(Evenement::class)->findAll();
        return $this->render('evenement/home.html.twig' , ['events'=>$list]);
    }


}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('app_evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{#  {{ form_start(form) }} #}
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/evenement/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/evenement/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Evenement</h1>
    {% for message in app.flashes('info')  %}
        <div class="alert alert-success">
            {{ message }}

        </div>



    {% endfor %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_event</th>
                <th>Nbr_participant</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Emplacement</th>
                <th>Description</th>
                <th>Theme</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.nomEvent }}</td>
                <td>{{ evenement.nbrParticipant }}</td>
                <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.emplacement }}</td>
                <td>{{ evenement.description }}</td>
                <td>{{ evenement.theme }}</td>
                <td>
                    <a href="{{ path('app_evenement_show', {'id': evenement.id}) }}" class="btn btn-fill-out btn-block ">show</a>
                    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}" class="btn btn-fill-out btn-block ">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
     
        </tbody>
          <center>  <div class="text-center">
            <div class="navigation">
                {{ knp_pagination_render(evenements) }}
            </div>
        </div></center>
    </table>
    <div class="text-center">
            <div class="navigation">
                {{ knp_pagination_render(evenements) }}
            </div>
        </div>


    <a href="{{ path('app_evenement_new') }}" class="btn btn-fill-out btn-block ">Create new</a>



    <a href="#" class="btn btn-fill-out btn-block ">Show All</a>
</div>

{% endblock %}

templates/evenement/indexFront.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <div class="container d-flex flex-column align-items-center">
        <h1>Evenement</h1>
        {% for message in app.flashes('info')  %}
            <div class="alert alert-success">
                {{ message }}

            </div>



        {% endfor %}

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom_event</th>
                <th>Nbr_participant</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Emplacement</th>
                <th>Description</th>
                <th>Theme</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for evenement in evenements %}
                <tr>
                    <td>{{ evenement.id }}</td>
                    <td>{{ evenement.nomEvent }}</td>
                    <td>{{ evenement.nbrParticipant }}</td>
                    <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d') : '' }}</td>
                    <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
                    <td>{{ evenement.emplacement }}</td>
                    <td>{{ evenement.description }}</td>
                    <td>{{ evenement.theme }}</td>
                    <td>
                        <a href="{{ path('app_evenement_show', {'id': evenement.id}) }}" class="btn btn-fill-out btn-block ">show</a>
                        <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}" class="btn btn-fill-out btn-block ">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_event_ticket') }}" class="btn btn-fill-out btn-block ">Participer</a>
        <a href="#" class="btn btn-fill-out btn-block ">Show All</a>
    </div>
{% endblock %}

templates/evenement/listp.html.twig
<table class="table">
    <tbody>

    {% for evenement in evenement %}


        <tr>
            <th>Nom_event</th>
            <td>{{ evenement.nomEvent }}</td>
        </tr>
        <tr>
            <th>Nbr_participant</th>
            <td>{{ evenement.nbrParticipant }}</td>
        </tr>
        <tr>
            <th>Date_debut</th>
            <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Date_fin</th>
            <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Emplacement</th>
            <td>{{ evenement.emplacement }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ evenement.description }}</td>
        </tr>
        <tr>
            <th>Theme</th>
            <td>{{ evenement.theme }}</td>
        </tr>
    {% endfor %}


    </tbody>
</table>

templates/evenement/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Evenement{% endblock %}

{% block body %}



<div class="container d-flex flex-column align-items-center">
    <h1>Create new Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('app_evenement_index') }}">back to list</a>
</div>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
<div class="container d-flex flex-column align-items-center">
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Image</th>
                <td><img src ="{{ asset('uploads/images/' ~ evenement.image) }}"
                     alt ="" style = "width: auto; height: auto">
                </td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Nom_event</th>
                <td>{{ evenement.nomEvent }}</td>
            </tr>
            <tr>
                <th>Nbr_participant</th>
                <td>{{ evenement.nbrParticipant }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
           
            <tr>
                <th>Description</th>
                <td>{{ evenement.description }}</td>
            </tr>
            <tr>
                <th>Theme</th>
                <td>{{ evenement.theme }}</td>
            </tr>

        </tbody>
    </table>
 <h4>
        <iframe style="border:0; width: 100%; height: 350px;" class="img-fluid" src="https://maps.google.com/maps?q=+
{{ evenement.emplacement }}+&hl=fr&z=14&amp;output=embed" frameborder="0" allowfullscreen>

        </iframe></h4>


    <a href="{{ path('app_evenement_index') }}">back to list</a>

    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}">edit</a>
    <a href="{{ path('listp', {'id': evenement.id}) }}">Telecharger comme PDF</a>
    {{ include('evenement/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/evenement/showFront.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}

        {% for Event in events %}

            <tbody>
            <tr>
                <th>Image</th>
                <td><img src ="{{ asset('uploads/images/' ~ Event.image) }}"
                         alt ="" style = "width: auto; height: auto">
                </td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ Event.id }}</td>
            </tr>
            <tr>
                <th>Nom_event</th>
                <td>{{ Event.nomEvent }}</td>
            </tr>
            <tr>
                <th>Nbr_participant</th>
                <td>{{ Event.nbrParticipant }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ Event.dateDebut ? Event.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ Event.dateFin ? Event.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Emplacement</th>
                <td>{{ Event.emplacement }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ Event.description }}</td>
            </tr>
            <tr>
                <th>Theme</th>
                <td>{{ Event.theme }}</td>
            </tr>

            </tbody>


        {% endfor %}
{% endblock %}